# Generated by Django 4.2.1 on 2023-06-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('textOfPaper', models.TextField(verbose_name='ТекстСтатьи')),
                ('pictureOfPaper', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
