# Generated by Django 4.2.1 on 2023-06-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_alter_profile_city_alter_profile_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='images/ProfilePhoto.jpg', upload_to='images/'),
        ),
    ]
