# Generated by Django 4.2.1 on 2023-06-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0003_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='control_response',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='security_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
